import React from "react";
import {
  ScrollView,
  Text,
  StyleSheet,
  View,
  Linking,
  TouchableOpacity,
} from "react-native";
import { moderateScale } from "react-native-size-matters";
import { colors, FONTS } from "@/constants/theme";
import { StatusBar } from "expo-status-bar";
import { SafeAreaView } from "react-native-safe-area-context";

export default function PrivacyScreen() {
  const openEmail = () => {
    Linking.openURL("mailto:admin@infinityarthvishva.com");
  };

  return (
    <SafeAreaView style={styles.safeArea} edges={["bottom"]}>
      <StatusBar style="light" />
      <ScrollView
        contentContainerStyle={styles.container}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.lastUpdated}>Last Updated: November 10, 2025</Text>

        {/* 1. Introduction */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>1. Introduction</Text>
          <Text style={styles.paragraph}>
            This Privacy Policy (hereinafter referred to as "Policy") is an
            electronic record governed by the Information Technology Act, 2000
            ("IT Act") and its allied rules, regulations, and guidelines. This
            Policy is generated by a computer system and does not require
            physical or electronic authentication.
          </Text>
        </View>

        {/* 2. Definitions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>2. Definitions</Text>

          <Text style={styles.subHeading}>User/Client</Text>
          <Text style={styles.paragraph}>
            refers to the individual accessing or using the Website and/or
            Mobile Application.
          </Text>

          <Text style={styles.subHeading}>Company</Text>
          <Text style={styles.paragraph}>
            refers to Infinity Arthvishva and its affiliates or subsidiaries.
          </Text>

          <Text style={styles.subHeading}>Site/Website</Text>
          <Text style={styles.paragraph}>
            refers to www.infinityarthvishva.com and any other website owned or
            operated by the Company.
          </Text>

          <Text style={styles.subHeading}>Personal Information</Text>
          <Text style={styles.paragraph}>
            refers to any personal data provided by the User in accordance with
            the Information Technology (Reasonable Security Practices and
            Procedures and Sensitive Personal Data) Rules, 2011.
          </Text>
        </View>

        {/* 3. Collection of Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>3. Collection of Information</Text>
          <Text style={styles.paragraph}>
            The Company collects personal and financial information from users,
            which may include:
          </Text>
          <View style={styles.bulletList}>
            <Text style={styles.bulletItem}>
              • Name, contact details (email, phone number), postal address,
              demographic profile
            </Text>
            <Text style={styles.bulletItem}>
              • Financial information, preferences regarding insurance or loan
              services
            </Text>
            <Text style={styles.bulletItem}>
              • Other relevant data necessary for providing our services
            </Text>
          </View>
          <Text style={styles.paragraph}>
            Additionally, anonymous information may be collected, such as IP
            address, browser type, device details, and usage patterns, primarily
            for website optimization purposes.
          </Text>
        </View>

        {/* 4. Data Security Measures */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>4. Data Security Measures</Text>
          <Text style={styles.paragraph}>
            The Company has implemented reasonable security practices and
            procedures to protect users' personal data in compliance with the IT
            Act, 2000. However, the Company is not liable for any data loss that
            may occur beyond its reasonable control.
          </Text>
        </View>

        {/* 5. Privacy Protection Principles */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            5. Privacy Protection Principles
          </Text>

          <Text style={styles.subHeading}>Security</Text>
          <Text style={styles.paragraph}>
            The Company employs various security technologies to safeguard
            users' personal information from unauthorized access, use, or
            disclosure.
          </Text>

          <Text style={styles.subHeading}>Choice</Text>
          <Text style={styles.paragraph}>
            Users may choose whether to provide their personal information,
            although failure to do so may limit access to certain services.
          </Text>

          <Text style={styles.subHeading}>Notice</Text>
          <Text style={styles.paragraph}>
            The Company collects personal information only for legitimate
            purposes and does not share it with third parties without user
            consent, unless required by law.
          </Text>

          <Text style={styles.subHeading}>Access/Accuracy</Text>
          <Text style={styles.paragraph}>
            Users can update or correct their personal information upon request.
          </Text>
        </View>

        {/* 6. Consent */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>6. Consent</Text>
          <Text style={styles.paragraph}>
            By using the Website and Mobile Application, the User consents to
            the collection, use, and processing of their personal data as
            outlined in this Privacy Policy. Users also agree to receive
            communication related to services, products, and promotions from the
            Company and its partners.
          </Text>
        </View>

        {/* 7. Sharing of Personal Data */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>7. Sharing of Personal Data</Text>
          <Text style={styles.paragraph}>
            The Company may share users' personal data with partners, service
            providers, and regulatory authorities as necessary for service
            delivery, legal obligations, or to prevent fraud. All data sharing
            is done on a need-to-know basis, and users' data will not be rented
            or sold.
          </Text>
        </View>

        {/* 8. Cookies */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>8. Cookies</Text>
          <Text style={styles.paragraph}>
            The Company uses cookies to enhance user experience. Cookies help
            personalize services, but users have the option to disable them
            through their browser settings. If cookies are disabled, some
            features may be limited.
          </Text>
        </View>

        {/* 9. Changes to Privacy Policy */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>9. Changes to Privacy Policy</Text>
          <Text style={styles.paragraph}>
            The Company reserves the right to modify this Privacy Policy at any
            time without prior notice. The revised Policy will be posted on this
            page, with the effective date indicated.
          </Text>
        </View>

        {/* 10. User Rights and Data Retention */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            10. User Rights and Data Retention
          </Text>
          <Text style={styles.paragraph}>
            Users may request to delete their account or revoke consent for data
            processing by contacting the Company at{" "}
            <Text style={styles.link} onPress={openEmail}>
              admin@infinityarthvishva.com
            </Text>
            . The Company will retain user data as long as required for legal or
            operational purposes and in accordance with applicable laws.
          </Text>
        </View>

        {/* 11. Third-Party Links */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>11. Third-Party Links</Text>
          <Text style={styles.paragraph}>
            The Company is not responsible for the privacy practices of
            third-party websites or services linked to or from the Website.
            Users are advised to review the privacy policies of third parties
            before providing personal information.
          </Text>
        </View>

        {/* 12. Contact Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>12. Contact Information</Text>
          <Text style={styles.paragraph}>
            For any queries, concerns, or suggestions regarding this Privacy
            Policy, users may contact the Company at{" "}
            <Text style={styles.link} onPress={openEmail}>
              admin@infinityarthvishva.com
            </Text>
            .
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.Base_Background,
  },
  container: {
    paddingHorizontal: moderateScale(20),
    paddingTop: moderateScale(24),
    paddingBottom: moderateScale(40),
  },
  lastUpdated: {
    fontFamily: FONTS.medium,
    fontSize: moderateScale(13),
    color: "#64748B",
    marginBottom: moderateScale(24),
  },
  section: {
    marginBottom: moderateScale(24),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: moderateScale(16),
    color: "#0F172A",
    marginBottom: moderateScale(10),
  },
  subHeading: {
    fontFamily: FONTS.semiBold,
    fontSize: moderateScale(14),
    color: "#1E293B",
    marginTop: moderateScale(12),
    marginBottom: moderateScale(4),
  },
  paragraph: {
    fontFamily: FONTS.regular,
    fontSize: moderateScale(14),
    color: "#475569",
    lineHeight: moderateScale(22),
  },
  bulletList: {
    marginVertical: moderateScale(8),
    paddingLeft: moderateScale(8),
  },
  bulletItem: {
    fontFamily: FONTS.regular,
    fontSize: moderateScale(14),
    color: "#475569",
    lineHeight: moderateScale(22),
    marginBottom: moderateScale(6),
  },
  link: {
    fontFamily: FONTS.semiBold,
    color: colors.Brand_Blue,
  },
});
