import React from "react";
import { ScrollView, Text, StyleSheet, View } from "react-native";
import { moderateScale } from "react-native-size-matters";
import { colors, FONTS } from "@/constants/theme";
import { StatusBar } from "expo-status-bar";
import { SafeAreaView } from "react-native-safe-area-context";

export default function TermsScreen() {
  return (
    <SafeAreaView style={styles.safeArea} edges={["bottom"]}>
      <StatusBar style="light" />
      <ScrollView
        contentContainerStyle={styles.container}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.lastUpdated}>
          Effective Date: November 10, 2025
        </Text>

        <Text style={styles.paragraph}>
          This document ("Terms of Use" or "TOU") is an electronic record under
          applicable Information Technology laws. It has been generated by a
          computer system and does not require physical authentication.
        </Text>

        {/* Important Notice Box */}
        <View style={styles.importantBox}>
          <Text style={styles.importantTitle}>Important:</Text>
          <Text style={styles.importantText}>
            By accessing www.infinityarthvishva.com or the Infinity Arthvishva
            mobile application (the "Site" or "Website"), you agree to the terms
            of this legal agreement between you ("User") and Infinity Arthvishva
            (the "Company").
          </Text>
        </View>

        {/* Company Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Company Information</Text>
          <Text style={styles.paragraph}>
            The Company is incorporated under the Companies Act, 2013, with its
            registered office at:
            {"\n\n"}
            <Text style={{ fontFamily: FONTS.semiBold }}>
              7 Business Square by Naiknavare, Ganeshkhind Rd, Model Colony,
              Shivajinagar, Pune, Maharashtra 411016.
            </Text>
          </Text>
        </View>

        {/* Definitions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Definitions</Text>

          <Text style={styles.subHeading}>"User", "Client", or "You"</Text>
          <Text style={styles.paragraph}>
            Refers to the individual using the Website/Mobile Application.
          </Text>

          <Text style={styles.subHeading}>"Company"</Text>
          <Text style={styles.paragraph}>
            Refers to Infinity Arthvishva and its affiliates/subsidiaries.
          </Text>

          <Text style={styles.subHeading}>"Site" or "Website"</Text>
          <Text style={styles.paragraph}>
            Refers to www.infinityarthvishva.com and associated sites, including
            content such as software, materials, text, images, videos, and
            applications.
          </Text>

          <Text style={styles.subHeading}>"Product" or "Services"</Text>
          <Text style={styles.paragraph}>
            Refers to financial and insurance products and services, including
            general insurance, life insurance, and related services provided by
            the Company.
          </Text>
        </View>

        {/* Services */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Services</Text>
          <Text style={styles.paragraph}>
            The Company distributes financial products like loans, mortgages,
            and insurance. By using the Website/Mobile Application, you agree to
            these terms.
          </Text>

          <Text style={styles.subHeading}>Access & Termination</Text>
          <Text style={styles.paragraph}>
            The Company may suspend or terminate your access if you violate
            these terms, privacy policies, or applicable laws.
          </Text>

          <Text style={styles.subHeading}>Information Sharing</Text>
          <Text style={styles.paragraph}>
            The User consents to the sharing of their information with third
            parties at the Company's discretion and with group companies.
          </Text>

          <Text style={styles.subHeading}>Electronic Communications</Text>
          <Text style={styles.paragraph}>
            The User agrees that all agreements, notices, disclosures, and other
            communications provided electronically satisfy any legal requirement
            for written communications.
          </Text>
        </View>

        {/* Detailed Terms */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Detailed Terms</Text>

          <Text style={styles.subHeading}>Feedback</Text>
          <Text style={styles.paragraph}>
            Unless explicitly stated otherwise, all comments, feedback,
            information, or materials submitted to the Company via this
            Website/Mobile Application will be considered the Company's
            property. By submitting such content, the User assigns all worldwide
            rights, including intellectual property rights, to the Company.
          </Text>

          <Text style={styles.subHeading}>Ownership</Text>
          <Text style={styles.paragraph}>
            The Website/Mobile Application contains various information and
            materials protected by intellectual property rights owned by the
            Company, its affiliates, subsidiaries, or third parties. All
            trademarks and copyrighted content are the property of their
            respective owners.
          </Text>

          <Text style={styles.subHeading}>User Responsibilities</Text>
          <Text style={styles.paragraph}>
            The User is solely responsible for maintaining the confidentiality
            of their password and Login ID. The User agrees to provide true,
            accurate, and complete information and promptly update it as needed.
          </Text>

          <Text style={styles.subHeading}>Eligibility and Use</Text>
          <Text style={styles.paragraph}>
            By using the Website/Mobile Application, the User confirms they are
            of legal age to form a binding contract and not barred from
            receiving services under applicable laws. Users may only maintain
            one active account.
          </Text>

          <Text style={styles.subHeading}>Third-Party Links/Offers</Text>
          <Text style={styles.paragraph}>
            The Website may include links to third-party websites. The Company
            is not responsible for their availability or content and does not
            endorse materials provided by these external resources.
          </Text>
        </View>

        {/* Footer Acknowledgment */}
        <View style={[styles.section, styles.footerSection]}>
          <Text style={styles.footerText}>
            By using this Website/Mobile Application, you acknowledge that you
            have read, understood, and agree to be bound by these Terms of Use.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.Base_Background,
  },
  container: {
    paddingHorizontal: moderateScale(20),
    paddingTop: moderateScale(24),
    paddingBottom: moderateScale(40),
  },
  lastUpdated: {
    fontFamily: FONTS.medium,
    fontSize: moderateScale(13),
    color: "#64748B",
    marginBottom: moderateScale(16),
  },
  importantBox: {
    backgroundColor: `${colors.Warning_Yellow}15`,
    borderColor: `${colors.Warning_Yellow}40`,
    borderWidth: 1,
    borderRadius: moderateScale(12),
    padding: moderateScale(16),
    marginVertical: moderateScale(20),
  },
  importantTitle: {
    fontFamily: FONTS.extraBold,
    fontSize: moderateScale(14),
    color: "#B45309", // Darker amber for contrast
    marginBottom: moderateScale(6),
  },
  importantText: {
    fontFamily: FONTS.medium,
    fontSize: moderateScale(13),
    color: "#92400E",
    lineHeight: moderateScale(20),
  },
  section: {
    marginBottom: moderateScale(24),
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: moderateScale(18),
    color: "#0F172A",
    marginBottom: moderateScale(12),
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: moderateScale(8),
  },
  subHeading: {
    fontFamily: FONTS.semiBold,
    fontSize: moderateScale(14),
    color: "#1E293B",
    marginTop: moderateScale(16),
    marginBottom: moderateScale(6),
  },
  paragraph: {
    fontFamily: FONTS.regular,
    fontSize: moderateScale(14),
    color: "#475569",
    lineHeight: moderateScale(22),
  },
  footerSection: {
    marginTop: moderateScale(10),
    backgroundColor: "#F8FAFC",
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  footerText: {
    fontFamily: FONTS.semiBold,
    fontSize: moderateScale(13),
    color: "#334155",
    lineHeight: moderateScale(20),
    textAlign: "center",
  },
});
